learning_users/basic/urls.py
from django.urls import path
from basic import views

app_name = 'basic'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.registration,name='registration'),
    path('logout/',views.user_Logout,name='Logout'),
    path('login/',views.user_Login,name='Login'),
    path('special/',views.special,name='special'),


]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('',include('basic.urls')),
    path("admin/", admin.site.urls),
]

learning_users/basic/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic/forms.py
from django import forms
from django.contrib.auth.models import User
from basic.models import UserProfileInfo
 
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic/views.py
from django.shortcuts import render
from basic.forms import UserForm,UserProfileInfoForm
#
from django.contrib.auth import authenticate,login,logout
from django.http import  HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'index.html')

@login_required
def special(request):
    return HttpResponse("You are loged in")

@login_required
def user_Logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic:index'))
    
def registration(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() & profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
             print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_Login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('basic:index'))
            else:
                return HttpResponse("Account not Active")
        else:
            print("Login Failed")
            print("Username:{} and password:{}".format(username,password))
            return HttpResponse("Invalid login details")
    else:
        return render(request,'login.html',{})

                

learning_users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic:index' %}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic:registration' %}"> Registration</a></li>

                {% if user.is_authenticated %}
                   <li><a class="navbar-link" href="{% url 'basic:Logout' %}">Logout</a></li>

                {% else %}

                   <li><a class="navbar-link" href="{% url 'basic:Login' %}">Login</a></li>
                  
                {% endif %}

            </ul>

        </div>

    </nav>
    <div class="container">
        {% block body_block %}
          
        {% endblock body_block %}

    </div>
    
</body>
</html>

learning_users/templates/index.html
{% extends 'base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h1>Wellcome to Django Level 5</h1>
</div>
{% endblock body_block %}

learning_users/templates/login.html
{% extends "base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic:Login' %}" method="POST">
         {% csrf_token %}
         <label for="username">Username:</label>
         <input type="text" placeholder="Enter Username" name="username">
         <label for="password">Password:</label>
         <input type="password" name="password">
         <input type="submit" value="Login" >

    </form>

</div>
  
{% endblock body_block %}

learning_users/templates/registration.html
{% extends "base.html" %}

{% load static %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registration</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Fill Out Your Form:</h3>
    <form method="POST" enctype="multipart/form-data">
         {% csrf_token %}
         {{ user_form.as_p }}
         {{ profile_form.as_p }}
         <input type="submit" value="Register" class="btn btn-primary">
        
    </form>
    {% endif %}

</div>
  
{% endblock body_block %}